import pytest

from cascade.db import ADK_MANAGED_TABLES, Base, exclude_adk_session_tables_from_autogenerate


@pytest.mark.parametrize("table_name", sorted(ADK_MANAGED_TABLES))
def test_adk_session_tables_are_never_autogenerated(table_name):
    assert exclude_adk_session_tables_from_autogenerate(table_name, "table", {}) is False


@pytest.mark.parametrize("table_name", ["runs", "card_events", "jobs", "decisions", "artifacts"])
def test_cascade_tables_are_autogenerated(table_name):
    assert exclude_adk_session_tables_from_autogenerate(table_name, "table", {}) is True


def test_non_table_objects_are_left_alone():
    assert exclude_adk_session_tables_from_autogenerate("state", "column", {}) is True


def test_no_cascade_table_collides_with_an_adk_table():
    assert set(Base.metadata.tables) & ADK_MANAGED_TABLES == set()
